"""Single parameter source for the ORBIT case study (millimetres)."""

PROJECT_ID = "orbit-cable-dock"
REVISION = "C"
CONFIGURATION = "prototype-fdm"

# Final product envelope and visual grammar
BASE_WIDTH = 96.0
BASE_DEPTH = 96.0
BASE_HEIGHT = 10.0
BASE_PLAN_RADIUS = 18.0
BASE_EDGE_RADIUS = 1.8

ROTOR_DIAMETER = 84.0
ROTOR_HEIGHT = 14.8
ROTOR_BOTTOM_Z = 11.2
ROTOR_EDGE_RADIUS = 2.2
SHADOW_GAP = ROTOR_BOTTOM_Z - BASE_HEIGHT

# Cable capture interface; concept/prototype assumptions, authority D
SLOT_COUNT = 4
SLOT_WIDTH = 6.4
SLOT_RADIAL_DEPTH = 18.0
SLOT_CUT_DEPTH = 8.0
SLOT_END_RADIUS = SLOT_WIDTH / 2.0

# Rotary support and retention; prototype assumptions, authority D
AXLE_DIAMETER = 10.0
AXLE_HEIGHT = 10.0
AXLE_PILOT_DIAMETER = 3.4
BUSHING_OD = 16.0
BUSHING_ID = 10.3
BUSHING_HEIGHT = 9.0
ROTOR_BORE_DIAMETER = 16.5
CAP_DIAMETER = 24.0
CAP_HEIGHT = 2.4
CAP_RECESS_DEPTH = 1.8

# Four indexed states; flexure force/life remain NOT_EVALUATED
DETENT_RADIUS = 31.5
DETENT_POCKET_DIAMETER = 4.4
DETENT_POCKET_DEPTH = 0.9
DETENT_INSERT_LENGTH = 16.0
DETENT_INSERT_WIDTH = 5.0
DETENT_INSERT_THICKNESS = 1.2
DETENT_NUB_DIAMETER = 2.8

ROTATION_MIN_DEG = 0.0
ROTATION_MAX_DEG = 360.0
INDEX_ANGLES_DEG = [0.0, 90.0, 180.0, 270.0]
REVIEW_ANGLES_DEG = [0.0, 45.0, 90.0, 180.0, 270.0]

# FDM prototype intent only; values are project assumptions, not vendor rules.
NOMINAL_WALL = 2.4
ROTARY_DIAMETRAL_CLEARANCE = ROTOR_BORE_DIAMETER - BUSHING_OD
AXLE_BUSHING_DIAMETRAL_CLEARANCE = BUSHING_ID - AXLE_DIAMETER

